# -----------------------------------------------
# clear-cdn-cache - Cloudflare CDNキャッシュ全パージ
#
# 前提:
#   - Cloudflare APIトークン (Zone.Cache Purge 権限)
#   - Cloudflare Zone ID
#
# 使い方:
#   - uses: ./.github/actions/clear-cdn-cache
#     with:
#       cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
#       cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
# -----------------------------------------------
name: 'CDNキャッシュ削除'
description: 'Cloudflare CDNキャッシュを全パージする'

inputs:
  cloudflare_zone_id:
    description: 'Cloudflare Zone ID (空の場合はスキップ)'
    required: false
    default: ''
  cloudflare_api_token:
    description: 'Cloudflare APIトークン (Zone.Cache Purge 権限、空の場合はスキップ)'
    required: false
    default: ''

outputs:
  success:
    description: 'キャッシュパージ成功かどうか (true/false)'
    value: ${{ steps.purge.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Cloudflareキャッシュをパージ
      id: purge
      shell: bash
      env:
        ZONE_ID: ${{ inputs.cloudflare_zone_id }}
        API_TOKEN: ${{ inputs.cloudflare_api_token }}
      run: |
        # 未設定チェック
        MISSING=""
        if [ -z "${ZONE_ID}" ]; then
          MISSING="${MISSING}  - CLOUDFLARE_ZONE_ID が未設定です\n"
        fi
        if [ -z "${API_TOKEN}" ]; then
          MISSING="${MISSING}  - CLOUDFLARE_API_TOKEN が未設定です\n"
        fi

        if [ -n "${MISSING}" ]; then
          echo "::warning::CDNキャッシュ削除をスキップします（以下のSecretsが未設定）:"
          echo -e "${MISSING}"
          echo "success=skipped" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "Cloudflare CDNキャッシュを全パージ中..."

        RESPONSE=$(curl -s -w "\n%{http_code}" \
          -X POST \
          -H "Authorization: Bearer ${API_TOKEN}" \
          -H "Content-Type: application/json" \
          -d '{"purge_everything":true}' \
          "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/purge_cache")

        HTTP_STATUS=$(echo "${RESPONSE}" | tail -n 1)
        BODY=$(echo "${RESPONSE}" | head -n -1)

        # レスポンスの success フィールドを確認
        SUCCESS=$(echo "${BODY}" | jq -r '.success // false')

        if [ "${SUCCESS}" = "true" ] && [ "${HTTP_STATUS}" -ge 200 ] && [ "${HTTP_STATUS}" -lt 300 ]; then
          echo "CDNキャッシュのパージに成功しました"
          echo "success=true" >> "$GITHUB_OUTPUT"
        else
          echo "::warning::CDNキャッシュのパージに失敗しました (HTTP ${HTTP_STATUS})。パイプラインは継続します"
          echo "${BODY}"
          echo "success=false" >> "$GITHUB_OUTPUT"
        fi
